spring:
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        globally_quoted_identifiers: true
        ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: inventory-docker-test-password
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  security:
    oauth2:
      resourceserver:
        jwt:
          # Domain of Auth0 tenant - INSERT HERE YOUR ISSUER URI FOR AUTH0 - (requires the trailing slash)
          issuer-uri: https://inventory-github.eu.auth0.com/

server:
  port: 3000

# API Identifier for the Auth0 API.
auth0:
  audience: inventory
